modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = '''${description}'''
authors = "${mod_author}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.forge.mixins.json"
